# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('active', '活跃'), ('blocked', '已屏蔽'), ('ended', '已结束')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_relationships', to=settings.AUTH_USER_MODEL, verbose_name='邀请者')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='用户1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='用户2')),
            ],
            options={
                'verbose_name': '关系',
                'verbose_name_plural': '关系',
                'db_table': 'relationships',
            },
        ),
        migrations.CreateModel(
            name='MaybeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_maybe_items', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maybe_items', to='relationships.relationship', verbose_name='关系')),
            ],
            options={
                'verbose_name': 'Maybe清单项',
                'verbose_name_plural': 'Maybe清单项',
                'db_table': 'maybe_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrowthGarden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_level', models.IntegerField(default=1, verbose_name='植物等级')),
                ('water_level', models.IntegerField(default=0, verbose_name='水分值')),
                ('last_watered_at', models.DateTimeField(blank=True, null=True, verbose_name='最后浇水时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growth_garden', to='relationships.relationship', verbose_name='关系')),
            ],
            options={
                'verbose_name': '成长花园',
                'verbose_name_plural': '成长花园',
                'db_table': 'growth_garden',
            },
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['user1', 'status'], name='relationshi_user1_i_ceffa2_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['user2', 'status'], name='relationshi_user2_i_4b2481_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('user1', 'user2')},
        ),
    ]
