# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200, verbose_name='物品')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('suggested_location', models.CharField(max_length=200, verbose_name='建议地点')),
                ('preparation_time', models.IntegerField(verbose_name='准备时间（分钟）')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('rejected', '不想要'), ('expired', '已过期'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='状态')),
                ('accepted_info', models.JSONField(blank=True, null=True, verbose_name='接受信息')),
                ('response', models.CharField(blank=True, choices=[('accepted', '好滴收下啦🥰'), ('rejected', '不太想要😅')], max_length=50, null=True, verbose_name='响应')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('has_expiration', models.BooleanField(default=False, verbose_name='是否有有效期')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='是否已撤回')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='最后编辑时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_gift_boxes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gift_boxes', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '心意盒',
                'verbose_name_plural': '心意盒',
                'db_table': 'gift_boxes',
                'indexes': [models.Index(fields=['created_by', 'status'], name='gift_boxes_created_f862a5_idx'), models.Index(fields=['target_user', 'status'], name='gift_boxes_target__9eda1c_idx'), models.Index(fields=['expires_at'], name='gift_boxes_expires_c71c92_idx')],
            },
        ),
    ]
