# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '协作邀请',
                'verbose_name_plural': '协作邀请',
                'db_table': 'collaboration_invitations',
                'indexes': [models.Index(fields=['created_by', 'status'], name='collaborati_created_ef8c45_idx'), models.Index(fields=['target_user', 'status'], name='collaborati_target__440202_idx'), models.Index(fields=['start_time'], name='collaborati_start_t_954c8d_idx')],
            },
        ),
    ]
