# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('current_energy_level', models.CharField(choices=[('🟢', '满血复活'), ('🟡', '血条还行'), ('🔴', '血槽空了'), ('⚪', '待规划')], default='⚪', max_length=10, verbose_name='当前能量状态')),
                ('focus_mode_enabled', models.BooleanField(default=False, verbose_name='专注模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超级用户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
