# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('record_type', models.CharField(choices=[('base', '基础状态'), ('planned', '预规划状态'), ('temporary', '临时状态')], max_length=20, verbose_name='记录类型')),
                ('energy_level', models.CharField(choices=[('🟢', '满血复活'), ('🟡', '血条还行'), ('🔴', '血槽空了'), ('⚪', '待规划')], max_length=10, verbose_name='能量等级')),
                ('time_slots', models.JSONField(default=list, verbose_name='时间段列表')),
                ('temporary_type', models.CharField(blank=True, choices=[('fastCharge', '快充模式'), ('lowPower', '低电量模式')], max_length=20, null=True, verbose_name='临时状态类型')),
                ('original_energy_level', models.CharField(blank=True, choices=[('🟢', '满血复活'), ('🟡', '血条还行'), ('🔴', '血槽空了'), ('⚪', '待规划')], max_length=10, null=True, verbose_name='原始能量状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '能量状态记录',
                'verbose_name_plural': '能量状态记录',
                'db_table': 'energy_records',
                'indexes': [models.Index(fields=['user', 'record_date'], name='energy_reco_user_id_d679bb_idx'), models.Index(fields=['record_type'], name='energy_reco_record__ca662d_idx')],
                'unique_together': {('user', 'record_date', 'record_type')},
            },
        ),
        migrations.CreateModel(
            name='EnergyLevelChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_time', models.DateTimeField(verbose_name='变更时间')),
                ('new_energy_level', models.CharField(choices=[('🟢', '满血复活'), ('🟡', '血条还行'), ('🔴', '血槽空了'), ('⚪', '待规划')], max_length=10, verbose_name='新能量状态')),
                ('change_type', models.CharField(choices=[('manual', '手动切换'), ('temporary', '临时状态'), ('planned', '预规划状态'), ('auto', '自动切换')], max_length=20, verbose_name='变更类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_level_changes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '能量状态变更历史',
                'verbose_name_plural': '能量状态变更历史',
                'db_table': 'energy_level_changes',
                'indexes': [models.Index(fields=['user', 'change_time'], name='energy_leve_user_id_3aa947_idx')],
            },
        ),
    ]
