# Generated by Django 4.2.7 on 2025-11-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='energyrecord',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='energyrecord',
            index=models.Index(fields=['user', 'record_date', 'record_type'], name='energy_reco_user_id_3b9798_idx'),
        ),
        # 添加部分唯一索引：base和planned类型在同一天只能有一条记录
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX energy_record_base_planned_unique 
                ON energy_records (user_id, record_date, record_type) 
                WHERE record_type IN ('base', 'planned');
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS energy_record_base_planned_unique;
            """
        ),
    ]
