# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片URL')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='链接URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='是否已撤回')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fragments', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_fragments', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '碎片',
                'verbose_name_plural': '碎片',
                'db_table': 'fragments',
                'indexes': [models.Index(fields=['created_by'], name='fragments_created_01bc08_idx'), models.Index(fields=['target_user', 'is_read'], name='fragments_target__19a9c0_idx'), models.Index(fields=['created_at'], name='fragments_created_b6292f_idx')],
            },
        ),
    ]
