# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeacefulClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closure_type', models.CharField(choices=[('item', '物品'), ('affair', '事务')], max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('item_details', models.JSONField(blank=True, null=True, verbose_name='物品详情')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('completed', '已完成'), ('archived', '已归档'), ('expired', '已过期'), ('cancelled', '已撤销')], default='pending', max_length=20, verbose_name='状态')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='响应信息')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('has_expiration', models.BooleanField(default=False, verbose_name='是否有过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_closures', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_closures', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '安心确认',
                'verbose_name_plural': '安心确认',
                'db_table': 'peaceful_closures',
                'indexes': [models.Index(fields=['created_by', 'status'], name='peaceful_cl_created_e42c8e_idx'), models.Index(fields=['target_user', 'status'], name='peaceful_cl_target__41d38a_idx'), models.Index(fields=['expires_at'], name='peaceful_cl_expires_ec2463_idx')],
            },
        ),
    ]
