# Generated by Django 4.2.7 on 2025-11-11 15:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None, verbose_name='图片URL列表')),
                ('is_text_hidden', models.BooleanField(default=True, verbose_name='文案是否隐藏')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_moments', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '瞬间',
                'verbose_name_plural': '瞬间',
                'db_table': 'moments',
                'indexes': [models.Index(fields=['created_by'], name='moments_created_03572e_idx'), models.Index(fields=['created_at'], name='moments_created_f40cfe_idx')],
            },
        ),
    ]
